### PR TITLE
Release 1.2

### PR DESCRIPTION
**Pull request by facundobatista**

### CODE REVIEW

**Review by sergio-costas — APPROVED** [review]
LGTM.

**Review by sergio-costas — APPROVED** [review]

**Review by mr-cal — APPROVED** [review]

**Comment by jugmac00** [comment]
As a user of `craft-cli`, it would be great to have a `CHANGES` or `NEWS` file.

**Comment by sergiusens** [comment]
Might be a good idea to add what we have for the other craft libraries, like https://github.com/canonical/craft-parts/blob/main/docs/changelog.rst

**Comment by facundobatista** [comment]
> Might be a good idea to add what we have for the other craft libraries, like https://github.com/canonical/craft-parts/blob/main/docs/changelog.rst

will do

**Pull request merged**
